version: '3'
services:
  app-go:
    container_name: app-go
    build:
      context: .docker/go
      dockerfile: Dockerfile
    environment:
      PORT: '8080'
    volumes:
      - ./src/:/go/src/app
    ports:
      - 8080:8080
    tty: true
    command: go run main.go

